### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by marminot** [TheKiritoPlayer20/Forge-Mods#10]
Language: [fr_fr]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Super Armure",
  "itemGroup.tools": "Outils",
  "itemGroup.supertools" : "Super Outils",
  "item.supertools.quartzhoe": "Houe en Quartz",
  "item.supertools.quartzaxe": "Hache en Quartz",
  "item.supertools.quartzpickaxe": "Pioche en Quartz",
  "item.supertools.quartzshovel": "Pelle en Quartz",
  "item.supertools.quartzsword": "Épée en Quartz",
  "item.supertools.emeraldhoe": "Houe en Émeraude",
  "item.supertools.emeraldaxe": "Hache en Émeraude",
  "item.supertools.emeraldpickaxe": "Pioche en Émeraude",
  "item.supertools.emeraldshovel": "Pelle en Émeraude",
  "item.supertools.emeraldsword": "Épée en Émeraude",
  "item.supertools.obsidianhoe": "Houe en Obsidienne",
  "item.supertools.obsidianaxe": "Hache en Obsidienne",
  "item.supertools.obsidianpickaxe": "Pioche en Obsidienne",
  "item.supertools.obsidianshovel": "Pelle en Obsidienne",
  "item.supertools.obsidiansword": "Épée en Obsidienne",
  "item.supertools.lapishoe": "Houe en Lapis-lazuli",
  "item.supertools.lapisaxe": "Hache en Lapis-lazuli",
  "item.supertools.lapispickaxe": "Pioche en Lapis-lazuli",
  "item.supertools.lapisshovel": "Pelle en Lapis-lazuli",
  "item.supertools.lapissword": "Épée en Lapis-lazuli",
  "item.supertools.redstonehoe": "Houe en Redstone",
  "item.supertools.redstoneaxe": "Hache en Redstone",
  "item.supertools.redstonepickaxe": "Pioche en Redstone",
  "item.supertools.redstoneshovel": "Pelle en Redstone",
  "item.supertools.redstonesword": "Épée en Redstone",
  "item.supertools.emeraldhelmet" : "Casque en Émeraude" ,
  "item.supertools.emeraldchestplate" : "Plastron en Émeraude",
  "item.supertools.emeraldleggings" : "Jambières en Émeraude",
  "item.supertools.emeraldboots" : "Bottes en Émeraude",
  "item.supertools.obsidianhelmet" : "Casque en Obsidienne",
  "item.supertools.obsidianchestplate" : "Plastron en Obsidienne",
  "item.supertools.obsidianleggings" : "Jambières en Obsidienne",
  "item.supertools.obsidianboots" : "Bottes en Obsidienne",
  "item.supertools.lapishelmet" : "Casque en Lapis-lazuli",
  "item.supertools.lapischestplate" : "Plastron en Lapis-lazuli",
  "item.supertools.lapisleggings" : "Jambières en Lapis-lazuli",
  "item.supertools.lapisboots" : "Bottes en Lapis-lazuli",
  "item.supertools.quartzhelmet" : "Casque en Quartz",
  "item.supertools.quartzchestplate" : "Plastron en Quartz",
  "item.supertools.quartzleggings" : "Jambières en Quartz",
  "item.supertools.quartzboots" : "Bottes en Quartz",
  "item.supertools.bonemealtool" : "Un sac de pourdre d‘os",
  "item.supertools.superhoe": "Super Houe",
  "item.supertools.superaxe": "Super Hache",
  "item.supertools.superpickaxe": "Super Pioche",
  "item.supertools.supershovel": "Super Pelle",
  "item.supertools.supersword": "Super Épée",
  "item.supertools.itemcup" : "Coupe",
  "item.supertools.specialcup" : "Coupe Spéciale",
  "item.supertools.woodensickle" : "Faucille en bois",
  "item.supertools.stonesickle" : "Faucille en pierre",
  "item.supertools.lapissickle" : "Faucille en Lapis-lazuli",
  "item.supertools.ironsickle" : "Faucille en fer",
  "item.supertools.redstonesickle" : "Faucille en Redstone",
  "item.supertools.goldensickle" : "Faucille en or",
  "item.supertools.diamondsickle" : "Faucille en diamant",
  "item.supertools.platinumsickle" : "Faucille en platine",
  "item.supertools.emeraldsickle" : "Faucille en Émeraude",
  "item.supertools.obsidiansickle" : "Faucille en Obsidienne",
  "item.supertools.quartzsickle" : "Faucille en Quartz",
  "item.supertools.supersickle" : "Super Faucille",
  "advancements.supertools.root.title" : "Super Outils",
  "advancements.supertools.root.description" : "fabrique tous les Super outils!",
  "advancements.supertools.superaxe.title" : "Super Hache",
  "advancements.supertools.superaxe.description" : "Est-ce une Super Hache?",
  "advancements.supertools.superpickaxe.title" : "Super Pioche",
  "advancements.supertools.superpickaxe.description" : "Est-ce une Super Pioche?",
  "advancements.supertools.supershovel.title" : "Super Pelle",
  "advancements.supertools.supershovel.description" : "Est-ce une Super Pelle?",
  "advancements.supertools.superhoe.title" : "Super Houe",
  "advancements.supertools.superhoe.description" : "Est-ce une Super Houe?",
  "advancements.supertools.supersword.title" : "Super Épée",
  "advancements.supertools.supersword.description" : "Est-ce une Super Épée?",
  "advancements.supertools.supersickle.title" : "Super Faucille",
  "advancements.supertools.supersickle.description" : "Est-ce une Super Faucille?",
  "advancements.supertools.bonemealtool.title" : "Un sac de poudre d‘os?",
  "advancements.supertools.bonemealtool.description" : "Pourquoi ne pas l‘utiliser pour fertiliser des plantes?",
  "advancements.supertools.cup.title" : "COUPE!",
  "advancements.supertools.cup.description" : "Pourquoi ne pas miner avec?",
  "advancements.supertools.specialcup.title" : "SUPER COUPE!",
  "advancements.supertools.specialcup.description" : "Pourquoi ne pas frapper des entités avec?"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the next version
