### ISSUE TITLE
Apex Server unable to run SuperTools due to "Incorrect" Forge version detected by SuperTools Mod.

### ISSUE THREAD

**Issue by maxwellevry** [TheKiritoPlayer20/Forge-Mods#11]
**Describe the bug**
Seems incorrect version of Forge is detected, currently running Minecraft ver. 1.15.2, with Forge ver. 1.15.2 on an Apex Server. When server attempts to start, console says:

09.02 08:46:41 [Server] INFO net.minecraftforge.fml.ModLoadingException: Mod supertools requires forge 31.1.0 or above
09.02 08:46:41 [Server] INFO Currently, forge is 31.0.19

Then the server crashes out as a result.

But surely this is incorrect, and no other mod I'm using is listing this as an issue, as they detect the 1.15.2 (31.1.0) version of Forge they all require, the most up to date version of Forge available to install at the moment.

**Versions**
Forge version: 31.1.0
Supertools version: 1.1

**Expected behavior**
I'd like to get my server running with SuperTools mod Installed.

**Screenshots**
![Minecraft Issue](https://user-images.githubusercontent.com/32979853/74103443-ebd94c00-4b43-11ea-999f-48ebc3ab58a5.JPG)

**Additional context**
I am not sure if this is anything you'd have experience in solving as an issue, but as it was only the SuperTools Mod that had this problem, I thought I'd come here first.

Any advice or guidance you could provide would be appreciated. Apex guidance on installing mods correctly was followed, and the server is able to start without SuperTools listed so hopefully not an issue with my Apex server, or with my Forge Version.

Thank you in advance.

**Comment by realKG20** [comment]
SuperTools need forge 31.1.0 or above. The other mods might not need it. SuperTools need it or atleast I told it to need it, as it is the recent stable version.
