### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by ManuelCan1** [TheKiritoPlayer20/Forge-Mods#14]
Language: [Spanish]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Super Armadura",
  "itemGroup.tools": "Herramientas",
  "itemGroup.supertools" : "Super Herramientas",
  "item.supertools.quartzhoe": "Azada de Cuarzo",
  "item.supertools.quartzaxe": "Hacha de Cuarzo",
  "item.supertools.quartzpickaxe": "Pico de Cuarzo",
  "item.supertools.quartzshovel": "Pala de Cuarzo",
  "item.supertools.quartzsword": "Espada de Cuarzo",
  "item.supertools.emeraldhoe": "Azada de Esmeralda",
  "item.supertools.emeraldaxe": "Hacha de Esmeralda",
  "item.supertools.emeraldpickaxe": "Pico de Esmeralda",
  "item.supertools.emeraldshovel": "Pala de Esmeralda",
  "item.supertools.emeraldsword": "Espada de Esmeralda",
  "item.supertools.obsidianhoe": "Azada de Obsidiana",
  "item.supertools.obsidianaxe": "Hacha de Obsidiana",
  "item.supertools.obsidianpickaxe": "Pico de Obsidiana",
  "item.supertools.obsidianshovel": "Pala de Obsidiana",
  "item.supertools.obsidiansword": "Espada de Obsidiana",
  "item.supertools.lapishoe": "Azada de Lapizlazuli",
  "item.supertools.lapisaxe": "Hacha de Lapizlazuli",
  "item.supertools.lapispickaxe": "Pico de Lapizlazuli",
  "item.supertools.lapisshovel": "Pala Lapizlazuli",
  "item.supertools.lapissword": "Espada de Lapizlazuli",
  "item.supertools.redstonehoe": "Azada de Redstone",
  "item.supertools.redstoneaxe": "Hacha de Redstone",
  "item.supertools.redstonepickaxe": "Pico de Redstone",
  "item.supertools.redstoneshovel": "Pala de Redstone",
  "item.supertools.redstonesword": "Espada de Redstone",
  "item.supertools.emeraldhelmet" : "Casco de Esmeralda",
  "item.supertools.emeraldchestplate" : "Pechera de Esmeralda",
  "item.supertools.emeraldleggings" : "Pantalones de Esmeralda",
  "item.supertools.emeraldboots" : "Botas de Esmeralda",
  "item.supertools.obsidianhelmet" : "Casco de Obsidiana",
  "item.supertools.obsidianchestplate" : "Pechera de Obsidiana",
  "item.supertools.obsidianleggings" : "Pantalones de Obsidiana",
  "item.supertools.obsidianboots" : "Botas de Obsidiana",
  "item.supertools.lapishelmet" : "Casco de Lapizlazuli",
  "item.supertools.lapischestplate" : "Pechera de Lapizlazuli",
  "item.supertools.lapisleggings" : "Pantalones de Lapizlazuli",
  "item.supertools.lapisboots" : "Botas de Lapizlazuli",
  "item.supertools.quartzhelmet" : "Casco de Cuarzo",
  "item.supertools.quartzchestplate" : "Pechera de Cuarzo",
  "item.supertools.quartzleggings" : "Pantalones de Cuarzo",
  "item.supertools.quartzboots" : "Botas de Cuarzo",
  "item.supertools.bonemealtool" : "Una bolsa de Hueso molido",
  "item.supertools.superhoe": "Super Azada",
  "item.supertools.superaxe": "Super Hacha",
  "item.supertools.superpickaxe": "Super Pico",
  "item.supertools.supershovel": "Super Pala",
  "item.supertools.supersword": "Super Espada",
  "item.supertools.itemcup" : "Copa",
  "item.supertools.specialcup" : "Copa Especial",
  "item.supertools.woodensickle" : "Hoz de Madera",
  "item.supertools.stonesickle" : "Hoz de Piedra",
  "item.supertools.lapissickle" : "Hoz de Lapizlazuli",
  "item.supertools.ironsickle" : "Hoz de Hierro",
  "item.supertools.redstonesickle" : "Hoz de Redstone",
  "item.supertools.goldensickle" : "Hoz de Oro",
  "item.supertools.diamondsickle" : "Hoz de Diamante",
  "item.supertools.emeraldsickle" : "Hoz de Esmeralda",
  "item.supertools.obsidiansickle" : "Hoz de Obsidiana",
  "item.supertools.quartzsickle" : "Hoz de Cuazo",
  "item.supertools.supersickle" : "Super Hoz",
  "advancements.supertools.root.title" : "Super Herramientas",
  "advancements.supertools.root.description" : "¡Haz todas las Super Herramientas!",
  "advancements.supertools.superaxe.title" : "Super Hacha",
  "advancements.supertools.superaxe.description" : "¿No es una Super Hacha?",
  "advancements.supertools.superpickaxe.title" : "Super Pico",
  "advancements.supertools.superpickaxe.description" : "¿No es un Super Pico?",
  "advancements.supertools.supershovel.title" : "Super Pala",
  "advancements.supertools.supershovel.description" : "¿No es una Super Pala?",
  "advancements.supertools.superhoe.title" : "Super Azada",
  "advancements.supertools.superhoe.description" : "¿No es una Super Azada?",
  "advancements.supertools.supersword.title" : "Super Espada",
  "advancements.supertools.supersword.description" : "¿No es una Super Espada?",
  "advancements.supertools.supersickle.title" : "Super Hoz",
  "advancements.supertools.supersickle.description" : "¿No es un Super Hoz?",
  "advancements.supertools.bonemealtool.title" : "¿Una bolsa de Hueso molido?",
  "advancements.supertools.bonemealtool.description" : "¿Porque no lo usas para fertilizar algunas plantas?",
  "advancements.supertools.cup.title" : "¡COPA!",
  "advancements.supertools.cup.description" : "¿Porque no vas a minar con esto?",
  "advancements.supertools.specialcup.title" : "SUPER COPA!",
  "advancements.supertools.specialcup.description" : "¿Porque no golpeas alguna entidad con esto? Traduccion Por ManuelCCH :)"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the next version.
