### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by Pioin** [TheKiritoPlayer20/Forge-Mods#15]
Language: [FR_fr]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Super Armure",
  "itemGroup.tools": "Outils",
  "itemGroup.supertools" : "Super Outils",
  "item.supertools.quartzhoe": "Houe en quartz",
  "item.supertools.quartzaxe": "Hache en quartz",
  "item.supertools.quartzpickaxe": "Pioche en quartz",
  "item.supertools.quartzshovel": "Pelle en quartz",
  "item.supertools.quartzsword": "Épée en quartz",
  "item.supertools.emeraldhoe": "Houe en émeraude",
  "item.supertools.emeraldaxe": "Hache en émeraude",
  "item.supertools.emeraldpickaxe": "Pioche en émeraude",
  "item.supertools.emeraldshovel": "Pelle en émeraude",
  "item.supertools.emeraldsword": "Épée en émeraude",
  "item.supertools.obsidianhoe": "Houe en obsidienne",
  "item.supertools.obsidianaxe": "Hache en obsidienne",
  "item.supertools.obsidianpickaxe": "Pioche en obsidienne",
  "item.supertools.obsidianshovel": "Pelle en obsidienne",
  "item.supertools.obsidiansword": "Épée en obsidienne",
  "item.supertools.lapishoe": "Houe en lapis",
  "item.supertools.lapisaxe": "Hache en lapis",
  "item.supertools.lapispickaxe": "Pioche en lapis",
  "item.supertools.lapisshovel": "Pelle en lapis",
  "item.supertools.lapissword": "Épée en lapis",
  "item.supertools.redstonehoe": "Houe en redstone",
  "item.supertools.redstoneaxe": "Hache en redstone",
  "item.supertools.redstonepickaxe": "Pioche en redstone",
  "item.supertools.redstoneshovel": "Pelle en redstone",
  "item.supertools.redstonesword": "Épée en redstone",
  "item.supertools.emeraldhelmet" : "Casque en émeraude",
  "item.supertools.emeraldchestplate" : "Plastron en émeraude",
  "item.supertools.emeraldleggings" : "Jambières en émeraude",
  "item.supertools.emeraldboots" : "Bottes en émeraude",
  "item.supertools.obsidianhelmet" : "Casque en obsidienne",
  "item.supertools.obsidianchestplate" : "Plastron en obsidienne",
  "item.supertools.obsidianleggings" : "Jambières en obsidienne",
  "item.supertools.obsidianboots" : "Bottes en obsidienne",
  "item.supertools.lapishelmet" : "Casque en lapis",
  "item.supertools.lapischestplate" : "Plastron en lapis",
  "item.supertools.lapisleggings" : "Jambières en lapis",
  "item.supertools.lapisboots" : "Bottes en lapis",
  "item.supertools.quartzhelmet" : "Casque en quartz",
  "item.supertools.quartzchestplate" : "Plastron en quartz",
  "item.supertools.quartzleggings" : "Jambières en quartz",
  "item.supertools.quartzboots" : "Bottes en quartz",
  "item.supertools.bonemealtool" : "Un sac de poudre d'os",
  "item.supertools.superhoe": "Super Houe",
  "item.supertools.superaxe": "Super Hache",
  "item.supertools.superpickaxe": "Super Pioche",
  "item.supertools.supershovel": "Super Pelle",
  "item.supertools.supersword": "Super Épée",
  "item.supertools.itemcup" : "Coupe",
  "item.supertools.specialcup" : "Coupe spéciale",
  "item.supertools.woodensickle" : "Faucille en bois",
  "item.supertools.stonesickle" : "Faucille en pierre",
  "item.supertools.lapissickle" : "Faucille en lapis",
  "item.supertools.ironsickle" : "Faucille en fer",
  "item.supertools.redstonesickle" : "Faucille en redstone",
  "item.supertools.goldensickle" : "Faucille en or",
  "item.supertools.diamondsickle" : "Faucille en diamant",
  "item.supertools.emeraldsickle" : "Faucille en émeraude",
  "item.supertools.obsidiansickle" : "Faucille en obsidienne",
  "item.supertools.quartzsickle" : "Faucille en quartz",
  "item.supertools.supersickle" : "Super Faucille",
  "advancements.supertools.root.title" : "Super Outils",
  "advancements.supertools.root.description" : "Fabrique tout les Super Outil!",
  "advancements.supertools.superaxe.title" : "Super hache",
  "advancements.supertools.superaxe.description" : "N'est-ce pas une Super Hache?",
  "advancements.supertools.superpickaxe.title" : "Super Pioche",
  "advancements.supertools.superpickaxe.description" : "N'est-ce pas une Super Pioche?",
  "advancements.supertools.supershovel.title" : "Super Pelle",
  "advancements.supertools.supershovel.description" : "N'est-ce pas une Super Pelle?",
  "advancements.supertools.superhoe.title" : "Super Houe",
  "advancements.supertools.superhoe.description" : "N'est-ce pas une Super Houe?",
  "advancements.supertools.supersword.title" : "Super Épée",
  "advancements.supertools.supersword.description" : "N'est-ce pas une Super Épée?",
  "advancements.supertools.supersickle.title" : "Super Faucille",
  "advancements.supertools.supersickle.description" : "N'est-ce pas une Super Faucille?",
  "advancements.supertools.bonemealtool.title" : "Un sac de poudre d'osl?",
  "advancements.supertools.bonemealtool.description" : "Pourquoi ne l'utilisez-vous pas et ne fertilisez-vous pas quelques plantes?",
  "advancements.supertools.cup.title" : "COUPE!",
  "advancements.supertools.cup.description" : "Pourquoi ne va-tu pas miner avec ?",
  "advancements.supertools.specialcup.title" : "SUPER COUPE!",
  "advancements.supertools.specialcup.description" : "Pourquoi ne frappez-vous aucune entité avec?"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the next update.
