### ISSUE TITLE
Recipes not working

### ISSUE THREAD

**Issue by FrAndromede** [TheKiritoPlayer20/Forge-Mods#16]
SuperTools-1.1_1.15.2.jar 

Tools are not craftable/have no recipes in 1.5.2 with Forge 1.15.2-31.1.0
No error is thrown, it just doesn't show up at the workbench.
Thank you for a great mod, hope it's a small fix :)

Forgot to mention something important, this is also installed on a Forge server.

**Comment by realKG20** [comment]
Are the recipes just not there or are they also not craftable and do you also have supertools installed as a client mod?
