### ISSUE TITLE
[TRANSLATION- Hungarian]

### ISSUE THREAD

**Issue by ExonHUN** [TheKiritoPlayer20/Forge-Mods#19]
Language: [Hungarian]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Szuper Páncél",
  "itemGroup.tools": "Eszközök",
  "itemGroup.supertools" : "Szuper Eszközök",
  "item.supertools.quartzhoe": "Kvarc Kapa",
  "item.supertools.quartzaxe": "Kvarc Balta",
  "item.supertools.quartzpickaxe": "Kvarc Csákány",
  "item.supertools.quartzshovel": "Kvarc Lapát",
  "item.supertools.quartzsword": "Kvarc Kard",
  "item.supertools.emeraldhoe": "Smaragd Kapa",
  "item.supertools.emeraldaxe": "Smaragd Balta",
  "item.supertools.emeraldpickaxe": "Smaragd Csákány",
  "item.supertools.emeraldshovel": "Smaragd Lapát",
  "item.supertools.emeraldsword": "Smaragd Kard",
  "item.supertools.obsidianhoe": "Obszidián Kapa",
  "item.supertools.obsidianaxe": "Obszidián Balta",
  "item.supertools.obsidianpickaxe": "Obszidián Csákány",
  "item.supertools.obsidianshovel": "Obszidián Lapát",
  "item.supertools.obsidiansword": "Obszidián Kard",
  "item.supertools.lapishoe": "Lapis Kapa",
  "item.supertools.lapisaxe": "Lapis Balta",
  "item.supertools.lapispickaxe": "Lapis Csákány",
  "item.supertools.lapisshovel": "Lapis Lapát",
  "item.supertools.lapissword": "Lapis Kard",
  "item.supertools.redstonehoe": "Vöröskő Kapa",
  "item.supertools.redstoneaxe": "Vöröskő Balta",
  "item.supertools.redstonepickaxe": "Vöröskő Csákány",
  "item.supertools.redstoneshovel": "Vöröskő Lapát",
  "item.supertools.redstonesword": "Vöröskő Kard",
  "item.supertools.emeraldhelmet" : "Smaragd Sisak",
  "item.supertools.emeraldchestplate" : "Smaragd Mellvért",
  "item.supertools.emeraldleggings" : "Smaragd Lábszárvédő",
  "item.supertools.emeraldboots" : "Smaragd Csizma",
  "item.supertools.obsidianhelmet" : "Obszidián Sisak",
  "item.supertools.obsidianchestplate" : "Obszidián Mellvért",
  "item.supertools.obsidianleggings" : "Obszidián Lábszárvédő",
  "item.supertools.obsidianboots" : "Obszidián Csizma",
  "item.supertools.lapishelmet" : "Lapis Sisak",
  "item.supertools.lapischestplate" : "Lapis Mellvért",
  "item.supertools.lapisleggings" : "Lapis Lábszárvédő",
  "item.supertools.lapisboots" : "Lapis Csizma",
  "item.supertools.quartzhelmet" : "Kvarc Sisak",
  "item.supertools.quartzchestplate" : "Kvarc Mellvért",
  "item.supertools.quartzleggings" : "Kvarc Lábszárvédő",
  "item.supertools.quartzboots" : "Kvarc Csizma",
  "item.supertools.bonemealtool" : "Egy zsáknyi Csontpor",
  "item.supertools.superhoe": "Szuper Kapa",
  "item.supertools.superaxe": "Szuper Balta",
  "item.supertools.superpickaxe": "Szuper Csákány",
  "item.supertools.supershovel": "Szuper Lapát",
  "item.supertools.supersword": "Szuper Kard",
  "item.supertools.itemcup" : "Csésze",
  "item.supertools.specialcup" : "Speciális Csésze",
  "item.supertools.woodensickle" : "Fa Sarló",
  "item.supertools.stonesickle" : "Kő Sarló",
  "item.supertools.lapissickle" : "Lapis Sarló",
  "item.supertools.ironsickle" : "Vas Sarló",
  "item.supertools.redstonesickle" : "Vöröskő Sarló",
  "item.supertools.goldensickle" : "Arany Sarló",
  "item.supertools.diamondsickle" : "Gyémánt Sarló",
  "item.supertools.emeraldsickle" : "Smaragd Sarló",
  "item.supertools.obsidiansickle" : "Obszidián Sarló",
  "item.supertools.quartzsickle" : "Kvarc Sarló",
  "item.supertools.supersickle" : "Szuper Sarló",
  "advancements.supertools.root.title" : "Szuper eszközök",
  "advancements.supertools.root.description" : "Készítsd el az összes Szuper Eszközt!",
  "advancements.supertools.superaxe.title" : "Szuper Balta",
  "advancements.supertools.superaxe.description" : "Ez nem egy Szuper Balta?",
  "advancements.supertools.superpickaxe.title" : "Szuper Csákány",
  "advancements.supertools.superpickaxe.description" : "Ez nem egy Szuper Csákány?",
  "advancements.supertools.supershovel.title" : "Szuper Lapát",
  "advancements.supertools.supershovel.description" : "Ez nem egy Szuper Lapát?",
  "advancements.supertools.superhoe.title" : "Szuper Kapa",
  "advancements.supertools.superhoe.description" : "Ez nem egy Szuper Kapa?",
  "advancements.supertools.supersword.title" : "Szuper Kard",
  "advancements.supertools.supersword.description" : "Ez nem egy Szuper Kard?",
  "advancements.supertools.supersickle.title" : "Szuper Sarló",
  "advancements.supertools.supersickle.description" : "Ez nem egy Szuper Sarló?",
  "advancements.supertools.bonemealtool.title" : "Egy zsáknyi Csontpor?",
  "advancements.supertools.bonemealtool.description" : "Miért nem trágyázol meg néhány növényt?",
  "advancements.supertools.cup.title" : "CSÉSZE!",
  "advancements.supertools.cup.description" : "Miért ne mmész bányászni vele?",
  "advancements.supertools.specialcup.title" : "SZUPER CSÉSZE!",
  "advancements.supertools.specialcup.description" : "Miért nem ütsz meg vele néhány ellenfelet?"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the next version.
