### ISSUE TITLE
Super tools not working in multiplayer server

### ISSUE THREAD

**Issue by rossi69** [TheKiritoPlayer20/Forge-Mods#20]
**Describe the bug**
I may be missing something as I can not find any info on this issue online, but I run my own dedicated server from my computer and have family members join from their computers, supertools works in single player but does not in the multiplayer server. I can get the tools in creative but they do not mine or dig more than one block at a time. 
I have reproduced this in a clean server with only supertools in the mods, am i missing something or do I require anything else to run this mod, or a setting change in the server config somewhere?

**Versions**
Forge version: 32.0.108
Supertools version: 1.0_16.1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by realKG20** [comment]
The server is also on forge 32.0.108? Did you make sure, all clients have the same supertools version as the server? For me it works just fine on a seperate Forge server.

**Comment by rossi69** [comment]
Hi There thanks for your prompt reply, I have tried this just now with a new forge server running 31.0.108 and also on the client and the only mod is the Supertools-1.0_1.16.1 on both the server and the client, it works fine in single player but as soon as i join the server i can get the tools but they only break one block and even then they display some strange behavior, with the pickaxe it seems to break the block 8 times before destroying just one block, the shovel does it in three hits. Is there anything else you can think off. do you need any more information?

**Comment by realKG20** [comment]
Did you download it from curseforge or Planetminecraft? just to make sure you got the official mod. Did you test it as an server operator and were you in creative mode or in survival mode? Also you may add the log from the server as this could help me.

**Comment by rossi69** [comment]
Downloaded it from Curseforge, and made myself OP in the server console went into creative to get the supertools then tested in survival. 
[latest.log](https://github.com/TheKiritoPlayer20/SuperTools/files/5288235/latest.log)

**Comment by realKG20** [comment]
Is this the full log or did you shorten it? I miss the part, where forge is being initialized with the mod...

**Comment by realKG20** [comment]
It seems like either forge or supertools was not initialized, on my test server it loaded 997 advancements and on your server only 927. Did you start the forge-1.16.1-32.0.108.jar?

**Comment by rossi69** [comment]
OK looks like I was pointing the run.bat at the wrong server and running the minecraft one not the forge.
Got it working now sorry for wasting your time.

Thanks A million

**Comment by realKG20** [comment]
No problem.
