### ISSUE TITLE
Sickles for modded materials

### ISSUE THREAD

**Issue by dmarkey32** [TheKiritoPlayer20/Forge-Mods#25]
Request for support for sickles using modded metals (Nickel, Copper, Zinc, etc.)  and alloys (Bronze, Invar, etc.) in SuperTools or a separate project (if this exists already, I apologize).  Similar to Spartan Weaponry/Spartan Shields.  Thank you and love your mod.

**Comment by realKG20** [comment]
Might be added. However there might be a problem, as forge will print out errors, if they won't find the ingredients for the recipe.
