### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by Harold1202** [TheKiritoPlayer20/Forge-Mods#27]
Language: [Español]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Super Armadura",
  "itemGroup.tools": "Herramientas",
  "itemGroup.supertools" : "Super Herramientas",
  "item.supertools.quartzhoe": "Azada de Cuarzo",
  "item.supertools.quartzaxe": "Hacha de Cuarzo",
  "item.supertools.quartzpickaxe": "Pico de Cuarzo",
  "item.supertools.quartzshovel": "Pala de Cuarzo",
  "item.supertools.quartzsword": "Espada de Cuarzo",
  "item.supertools.emeraldhoe": "Azada de Esmeralda",
  "item.supertools.emeraldaxe": "Hacha de Esmeralda",
  "item.supertools.emeraldpickaxe": "Pico de Esmeralda",
  "item.supertools.emeraldshovel": "Pala de Esmeralda",
  "item.supertools.emeraldsword": "Espada de Esmeralda",
  "item.supertools.obsidianhoe": "Azada de Obsidiana",
  "item.supertools.obsidianaxe": "Hacha de Obsidiana",
  "item.supertools.obsidianpickaxe": "Pico de Obsidiana",
  "item.supertools.obsidianshovel": "Pala de Obsidiana",
  "item.supertools.obsidiansword": "Espada de Obsidiana",
  "item.supertools.lapishoe": "Azada de Lapislázuli",
  "item.supertools.lapisaxe": "Hacha de Lapislázuli",
  "item.supertools.lapispickaxe": "Pico de Lapislázuli",
  "item.supertools.lapisshovel": "Pala de Lapislázuli",
  "item.supertools.lapissword": "Espada de Lapislázuli",
  "item.supertools.redstonehoe": "Azada de Redstone",
  "item.supertools.redstoneaxe": "Hacha de Redstone",
  "item.supertools.redstonepickaxe": "Pico de Redstone",
  "item.supertools.redstoneshovel": "Pala de Redstone",
  "item.supertools.redstonesword": "Espada de Redstone",
  "item.supertools.emeraldhelmet" : "Casco de Esmeralda",
  "item.supertools.emeraldchestplate" : "Peto de Esmeralda",
  "item.supertools.emeraldleggings" : "Grebas de Esmeralda",
  "item.supertools.emeraldboots" : "Botas de Esmeralda",
  "item.supertools.obsidianhelmet" : "Casco de Obsidiana",
  "item.supertools.obsidianchestplate" : "Peto de Obsidiana",
  "item.supertools.obsidianleggings": "Grebas de Obsidiana",
  "item.supertools.obsidianboots": "Botas de Obsidiana",
  "item.supertools.lapishelmet": "Casco de Lapislázuli",
  "item.supertools.lapischestplate": "Peto de Lapislázuli",
  "item.supertools.lapisleggings": "Grebas de Lapislázuli",
  "item.supertools.lapisboots": "Botas de Lapislázuli",
  "item.supertools.quartzhelmet": "Casco de cuarzo",
  "item.supertools.quartzchestplate": "Peto de cuarzo",
  "item.supertools.quartzleggings": "Grebas de cuarzo",
  "item.supertools.quartzboots": "Botas de cuarzo",
  "item.supertools.bonemealtool": "Una bolsa de harina de huesos",
  "item.supertools.superhoe": "Super Azada",
  "item.supertools.superaxe": "Súper Hacha",
  "item.supertools.superpickaxe": "Súper Pico",
  "item.supertools.supershovel": "Súper Pala",
  "item.supertools.supersword": "Súper Espada",
  "item.supertools.itemcup": "Copa",
  "item.supertools.specialcup": "Copa especial",
  "item.supertools.woodensickle": "Hoz de Madera",
  "item.supertools.stonesickle": "Hoz de Piedra",
  "item.supertools.lapissickle": "Hoz de Lapislázuli",
  "item.supertools.ironsickle": "Hoz de Hierro",
  "item.supertools.redstonesickle": "Hoz de Redstone",
  "item.supertools.goldensickle": "Hoz de Oro",
  "item.supertools.diamondsickle": "Hoz de Diamante",
  "item.supertools.platinumsickle": "Hoz de Platino",
  "item.supertools.emeraldsickle": "Hoz de Esmeralda",
  "item.supertools.obsidiansickle": "Hoz de Obsidiana",
  "item.supertools.quartzsickle": "Hoz de Cuarzo",
  "item.supertools.netheritesickle": "Hoz de Netherita",
  "item.supertools.supersickle": "Super Hoz",
  "advancements.supertools.root.title": "Super Herramientas",
  "advancements.supertools.root.description": "¡Crea todas las Super Herramientas!",
  "advancements.supertools.superaxe.title": "Súper Hacha",
  "advancements.supertools.superaxe.description": "¿No es una Super Hacha?",
  "advancements.supertools.superpickaxe.title": "Súper Pico",
  "advancements.supertools.superpickaxe.description": "¿No es un Super Pico?",
  "advancements.supertools.supershovel.title": "Súper Pala",
  "advancements.supertools.supershovel.description": "¿No es una Súper Pala?",
  "advancements.supertools.superhoe.title": "Super Azada",
  "advancements.supertools.superhoe.description": "¿No es una Super Azada?",
  "advancements.supertools.supersword.title": "Súper Espada",
  "advancements.supertools.supersword.description": "¿No es una Super Espada?",
  "advancements.supertools.supersickle.title": "Super Hoz",
  "advancements.supertools.supersickle.description": "¿No es una Super Hoz?",
  "advancements.supertools.bonemealtool.title": "¿Una bolsa de harina de huesos?",
  "advancements.supertools.bonemealtool.description": "¿Por qué no lo usas y fertilizas algunas plantas?",
  "advancements.supertools.cup.title": "¡COPA!",
  "advancements.supertools.cup.description": "¿Por qué no vas a minar con él?",
  "advancements.supertools.specialcup.title": "¡SUPER COPA!",
  "advancements.supertools.specialcup.description": "¿Por qué no golpea a alguna entidad con él?"
}

**Comment by realKG20** [comment]
Thanks! Will be added in the next update.
