### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by kek3ls** [TheKiritoPlayer20/Forge-Mods#28]
Language: [Russian]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Супер Броня",
  "itemGroup.tools": "Инструменты",
  "itemGroup.supertools" : "Супер Инструменты",
  "item.supertools.quartzhoe": "Кварцевая Мотыга",
  "item.supertools.quartzaxe": "Кварцевый Топор",
  "item.supertools.quartzpickaxe": "Кварцевая Кирка",
  "item.supertools.quartzshovel": "Кварцевая Лопата",
  "item.supertools.quartzsword": "Кварцевый Меч",
  "item.supertools.emeraldhoe": "Изумрудная Мотыга",
  "item.supertools.emeraldaxe": "Изумрудный Топор",
  "item.supertools.emeraldpickaxe": "Изумрудная Кирка",
  "item.supertools.emeraldshovel": "Изумрудная Лопата",
  "item.supertools.emeraldsword": "Изумрудный Меч",
  "item.supertools.obsidianhoe": "Обсидиановый Мотыга",
  "item.supertools.obsidianaxe": "Обсидиановый Топор",
  "item.supertools.obsidianpickaxe": "Обсидиановая Кирка",
  "item.supertools.obsidianshovel": "Обсидиановая Лопата",
  "item.supertools.obsidiansword": "Обсидиановый Меч",
  "item.supertools.lapishoe": "Лазуритовая Мотыга",
  "item.supertools.lapisaxe": "Лазуритовый Топор",
  "item.supertools.lapispickaxe": "Лазуритовая Кирка",
  "item.supertools.lapisshovel": "Лазуритовая Лопата",
  "item.supertools.lapissword": "Лазуритовый Меч",
  "item.supertools.redstonehoe": "Мотыга из Красного Камня",
  "item.supertools.redstoneaxe": "Топор из Красного Камня",
  "item.supertools.redstonepickaxe": "Кирка из Красного Камня",
  "item.supertools.redstoneshovel": "Лопата из Красного Камня",
  "item.supertools.redstonesword": "Меч из Красного Камня",
  "item.supertools.emeraldhelmet" : "Изумрудный Шлем",
  "item.supertools.emeraldchestplate" : "Изумрудный Нагрудник",
  "item.supertools.emeraldleggings" : "Изумрудные Поножи",
  "item.supertools.emeraldboots" : "Изумрудные Ботинки",
  "item.supertools.obsidianhelmet" : "Обсидиановый Шлем",
  "item.supertools.obsidianchestplate" : "Обсидиановый Нагрудник",
  "item.supertools.obsidianleggings" : "Обсидиановые Поножи",
  "item.supertools.obsidianboots" : "Обсидиановые Ботинки",
  "item.supertools.lapishelmet" : "Лазуритовый Шлем",
  "item.supertools.lapischestplate" : "Лазуритовый Нагрудник",
  "item.supertools.lapisleggings" : "Лазуритовые Поножи",
  "item.supertools.lapisboots" : "Лазуритовые Ботинки",
  "item.supertools.quartzhelmet" : "Кварцевый Шлем",
  "item.supertools.quartzchestplate" : "Кварцевый Нагрудник",
  "item.supertools.quartzleggings" : "Кварцевые Поножи",
  "item.supertools.quartzboots" : "Кварцевые Ботинки",
  "item.supertools.bonemealtool" : "Мешочек костной муки",
  "item.supertools.superhoe": "Супер Мотыга",
  "item.supertools.superaxe": "Супер Топор",
  "item.supertools.superpickaxe": "Супер Кирка",
  "item.supertools.supershovel": "Супер Лопата",
  "item.supertools.supersword": "Супер Меч",
  "item.supertools.itemcup" : "Чашка",
  "item.supertools.specialcup" : "Специальная чашка",
  "item.supertools.woodensickle" : "Деревянный Серп",
  "item.supertools.stonesickle" : "Каменный Серп",
  "item.supertools.lapissickle" : "Лазуритовый Серп",
  "item.supertools.ironsickle" : "Железный Серп",
  "item.supertools.redstonesickle" : "Серп из Красного Камня",
  "item.supertools.goldensickle" : "Золотой Серп",
  "item.supertools.diamondsickle" : "Алмазный Серп",
  "item.supertools.platinumsickle" : "Платиновый Серп",
  "item.supertools.emeraldsickle" : "Изумрудный Серп",
  "item.supertools.obsidiansickle" : "Обсидиановый Серп",
  "item.supertools.quartzsickle" : "Кварцевый Серп",
  "item.supertools.netheritesickle" : "Незеритовый Серп",
  "item.supertools.supersickle" : "Супер Серп",
  "advancements.supertools.root.title" : "Супер Инструменты",
  "advancements.supertools.root.description" : "Сделать каждый супер инструмент!",
  "advancements.supertools.superaxe.title" : "Супер Топор",
  "advancements.supertools.superaxe.description" : "Неужели это Супер Топор?",
  "advancements.supertools.superpickaxe.title" : "Супер Кирка",
  "advancements.supertools.superpickaxe.description" : "Неужели это Супер Кирка?",
  "advancements.supertools.supershovel.title" : "Супер Лопата",
  "advancements.supertools.supershovel.description" : "Неужели это Супер Лопата?",
  "advancements.supertools.superhoe.title" : "Супер Мотыга",
  "advancements.supertools.superhoe.description" : "Неужели это Супер Мотыга?",
  "advancements.supertools.supersword.title" : "Супер Меч",
  "advancements.supertools.supersword.description" : "Неужели это Супер Меч?",
  "advancements.supertools.supersickle.title" : "Супер Серп",
  "advancements.supertools.supersickle.description" : "Неужели это Супер Серп?",
  "advancements.supertools.bonemealtool.title" : "Мешочек костной муки?",
  "advancements.supertools.bonemealtool.description" : "Почему бы тебе не использовать его для удобрения растений?",
  "advancements.supertools.cup.title" : "ЧАШКА!",
  "advancements.supertools.cup.description" : "Почему бы тебе не пойти в шахту с ней?",
  "advancements.supertools.specialcup.title" : "Супер ЧАШКА!",
  "advancements.supertools.specialcup.description" : "Почему бы тебе не ударить ей кого или что-нибудь?"
}

**Comment by realKG20** [comment]
Will be added in the next update. Thanks
