### ISSUE TITLE
Super Tools Not Working With Natural Progression Mod

### ISSUE THREAD

**Issue by F3R07** [TheKiritoPlayer20/Forge-Mods#38]
Not a bug, but also not a feature request.

When trying to use the Super Pickaxe, it says "You need the right tool for this job".
How can the supertools work?

**Comment by realKG20** [comment]
I don't know how the mod works, but i guess the mod has its own Mining Tier list, which might be a problem. Which Blocks are you trying to mine with the Super Pickaxe?

**Comment by F3R07** [comment]
Just normal stone. Natural progression definitely has its own mining tier list, but I couldn't find anything related to it in the config files. For example, with this mod, wood and stone tools no longer work, it gives that message "you need the right tool for this job". I've also noticed it happens with the copper pickaxe with the Simple Ores mod. I also posted this issue on the natural progression mod page but I figured I'd ask in both places.

**Comment by realKG20** [comment]
I thought so. Guess it is something only natural progression can fix. Or atleast it is best if they fix it. I might be able to fix it in Super Tools but i don't think its the right approach.  

I will close this issue as "wont fix"

Edit: Also i won't fix it in my mod, as it is the intention of the modder (team) of Natural Progression to have it this way, so i won't interfere with it.
