### ISSUE TITLE
Hoe doesn't work

### ISSUE THREAD

**Issue by VsUK** [TheKiritoPlayer20/Forge-Mods#39]
**Describe the bug**
The hoe doesn't perform the tasks a hoe should do when right clicking on soil or plants to collect. This was reproduced using copper hoe & redstone hoe's. I can dig with it when left click, but right click functions don't do anything.

**Versions**
Supertools version: 1.19.2*

**Comment by realKG20** [comment]
Tested it just now. Every Material doesn't work. Will be fixed soon.
