### ISSUE TITLE
[TRANSLATION] French (fr_FR) translation

### ISSUE THREAD

**Issue by IyoudTaker** [TheKiritoPlayer20/Forge-Mods#41]
Language: [Language]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Armures Améliorées",
  "itemGroup.tools": "Outils",
  "itemGroup.supertools" : "Outils Améliorés",
  "item.supertools.quartzhoe": "Houe en Quartz",
  "item.supertools.quartzaxe": "Hache en Quartz",
  "item.supertools.quartzpickaxe": "Pioche en Quartz",
  "item.supertools.quartzshovel": "Pelle en Quartz",
  "item.supertools.quartzsword": "Épée en Quartz",
  "item.supertools.emeraldhoe": "Houe en Émeraude",
  "item.supertools.emeraldaxe": "Hache en Émeraude"
  "item.supertools.emeraldpickaxe": "Pioche en Émeraude",
  "item.supertools.emeraldshovel": "Pelle en Émeraude",
  "item.supertools.emeraldsword": "Épée en Émeraude",
  "item.supertools.obsidianhoe": "Houe en Obsidienne",
  "item.supertools.obsidianaxe": "Hache en Obsidienne",
  "item.supertools.obsidianpickaxe": "Pioche en Obsidienne",
  "item.supertools.obsidianshovel": "Pelle en Obsidienne",
  "item.supertools.obsidiansword": "Épée en Obsidienne",
  "item.supertools.lapishoe": "Houe en Lapis-lazuli",
  "item.supertools.lapisaxe": "Hache en Lapis-lazuli",
  "item.supertools.lapispickaxe": "Pioche en Lapis-lazuli",
  "item.supertools.lapisshovel": "Pelle en Lapis-lazuli",
  "item.supertools.lapissword": "Épée en Lapis-lazuli",
  "item.supertools.redstonehoe": "Houe en Redstone",
  "item.supertools.redstoneaxe": "Hache en Redstone",
  "item.supertools.redstonepickaxe": "Pioche en Redstone",
  "item.supertools.redstoneshovel": "Pelle en Redstone",
  "item.supertools.redstonesword": "Épée en Redstone",
  "item.supertools.emeraldhelmet" : "Casque en Émeraude",
  "item.supertools.emeraldchestplate" : "Plastron en Émeraude",
  "item.supertools.emeraldleggings" : "Jambières en Émeraude",
  "item.supertools.emeraldboots" : "Bottes en Émeraude",
  "item.supertools.obsidianhelmet" : "Casque en Obsidienne",
  "item.supertools.obsidianchestplate" : "Plastron en Obsidienne",
  "item.supertools.obsidianleggings" : "Jambières en Obsidienne",
  "item.supertools.obsidianboots" : "Bottes en Obsidienne",
  "item.supertools.lapishelmet" : "Casque en Lapis-lazuli",
  "item.supertools.lapischestplate" : "Plastron en Lapis-lazuli",
  "item.supertools.lapisleggings" : "Jambières en Lapis-lazuli",
  "item.supertools.lapisboots" : "Bottes en Lapis-lazuli",
  "item.supertools.quartzhelmet" : "Casque en Quartz",
  "item.supertools.quartzchestplate" : "Plastron en Quartz",
  "item.supertools.quartzleggings" : "Jambières en Quartz",
  "item.supertools.quartzboots" : "Bottes en Quartz",
  "item.supertools.bonemealtool" : "Sac de Poudre d’os",
  "item.supertools.superhoe": "Houe Améliorée",
  "item.supertools.superaxe": "Hache Améliorée",
  "item.supertools.superpickaxe": "Pioche Améliorée",
  "item.supertools.supershovel": "Pelle Améliorée",
  "item.supertools.supersword": "Épée Améliorée",
  "item.supertools.itemcup" : "Coupe",
  "item.supertools.specialcup" : "Coupe Améliorée",
  "item.supertools.woodensickle" : "Faucille en Bois",
  "item.supertools.stonesickle" : "Faucille en Pierre",
  "item.supertools.lapissickle" : "Faucille en Lapis-lazuli",
  "item.supertools.ironsickle" : "Faucille en Fer",
  "item.supertools.redstonesickle" : "Faucille en Redstone",
  "item.supertools.goldensickle" : "Faucille en Or",
  "item.supertools.diamondsickle" : "Faucille en Diamant",
  "item.supertools.platinumsickle" : "Faucille en Platine",
  "item.supertools.emeraldsickle" : "Faucille en Émeraude",
  "item.supertools.obsidiansickle" : "Faucille en Obsidienne",
  "item.supertools.quartzsickle" : "Faucille en Quartz",
  "item.supertools.netheritesickle" : "Faucille en Netherite",
  "item.supertools.supersickle" : "Faucille Améliorée",
  "advancements.supertools.root.title" : "Outils Améliorés",
  "advancements.supertools.root.description" : "Fabrique tous les outils améliorés !",
  "advancements.supertools.superaxe.title" : "Hache Améliorée",
  "advancements.supertools.superaxe.description" : "Cette hache semble meilleure, n’est-ce pas ?",
  "advancements.supertools.superpickaxe.title" : "Pioche Améliorée",
"advancements.supertools.superpickaxe.description" : "Cette pioche semble meilleure, n’est-ce pas ?",
  "advancements.supertools.supershovel.title" : "Pelle Améliorée",
  "advancements.supertools.supershovel.description" : "Cette pelle semble meilleure, n’est-ce pas ?",
  "advancements.supertools.superhoe.title" : "Super Hoe",
  "advancements.supertools.superhoe.description" : "Cette houe semble meilleure, n’est-ce pas ?",
  "advancements.supertools.supersword.title" : "Épée Améliorée",
  "advancements.supertools.supersword.description" : "Cette épée semble meilleure, n’est-ce pas ?",
  "advancements.supertools.supersickle.title" : "Faucille Améliorée",
  "advancements.supertools.supersickle.description" : "Cette faucille semble meilleure, n’est-ce pas ?",
  "advancements.supertools.bonemealtool.title" : "Un sac de poudre d’os ?",
  "advancements.supertools.bonemealtool.description" : "Essayez de fertiliser des plantes avec !",
  "advancements.supertools.cup.title" : "UNE COUPE!",
  "advancements.supertools.cup.description" Essayez de miner avec !",
  "advancements.supertools.specialcup.title" : "UNE SUPER COUPE !",
  "advancements.supertools.specialcup.description" : "Essayez d’aller vous battre avec !"
}

**Comment by realKG20** [comment]
Thank you. I will add it in the next release.
