### ISSUE TITLE
[TRANSLATION] ~ Polish

### ISSUE THREAD

**Issue by Kazix46** [TheKiritoPlayer20/Forge-Mods#8]
Language: [Polish]

To translate: just replace the old names, e.g to rename the "itemGroup.armor" replace "Super Armor" with the translation.

{
  "itemGroup.armor": "Wyśmienita Zbroja",
  "itemGroup.tools": "Narzędzia",
  "itemGroup.supertools" : "Super Narzędzia",
  "item.supertools.quartzhoe": "Kwarcowa Motyka",
  "item.supertools.quartzaxe": "Kwarcowa Siekiera",
  "item.supertools.quartzpickaxe": "Kwarcowy Kilof",
  "item.supertools.quartzshovel": "Kwarcowa Łopata",
  "item.supertools.quartzsword": "Kwarcowy Miecz",
  "item.supertools.emeraldhoe": "Szmaragdowa Motyka",
  "item.supertools.emeraldaxe": "Szmaragdowa Siekiera",
  "item.supertools.emeraldpickaxe": "Szmaragdowy Kilof",
  "item.supertools.emeraldshovel": "Szmaragdowa Łopata",
  "item.supertools.emeraldsword": "Szmaragdowy Miecz",
  "item.supertools.obsidianhoe": "Obsydianowa Motyka",
  "item.supertools.obsidianaxe": "Obsydianowa Siekiera",
  "item.supertools.obsidianpickaxe": "Obsydianowy Kilof",
  "item.supertools.obsidianshovel": "Obsydianowa Łopata",
  "item.supertools.obsidiansword": "Obsydianowy Miecz",
  "item.supertools.lapishoe": "Lazurytowa Motyka",
  "item.supertools.lapisaxe": "Lazurytowa Siekiera",
  "item.supertools.lapispickaxe": "Lazurytowy Kilof",
  "item.supertools.lapisshovel": "Lazurytowa Łopata",
  "item.supertools.lapissword": "Lazurytowy Miecz",
  "item.supertools.redstonehoe": "Redstonowa Motyka",
  "item.supertools.redstoneaxe": "Redstonowa Siekiera",
  "item.supertools.redstonepickaxe": "Redstonowy Kilof",
  "item.supertools.redstoneshovel": "Redstonowa Łopata",
  "item.supertools.redstonesword": "Redstonowy Miecz",
  "item.supertools.emeraldhelmet" : "Szmaragdowe Buty",
  "item.supertools.emeraldchestplate" : "Szmaragdowy Napierśnik",
  "item.supertools.emeraldleggings" : "Szmaragdowe Nogawice",
  "item.supertools.emeraldboots" : "Szmaragdowe Buty",
  "item.supertools.obsidianhelmet" : "Obsydianowy Hełm",
  "item.supertools.obsidianchestplate" : "Obsydianowy Napierśnik",
  "item.supertools.obsidianleggings" : "Obsydianowe Nogawice",
  "item.supertools.obsidianboots" : "Obsydianowe Buty",
  "item.supertools.lapishelmet" : "Lazurytowy Hełm",
  "item.supertools.lapischestplate" : "Lazurytowy Napierśnik",
  "item.supertools.lapisleggings" : "Lazurytowe Nogawice",
  "item.supertools.lapisboots" : "Lazurytowe Buty",
  "item.supertools.quartzhelmet" : "Kwarcowy Hełm",
  "item.supertools.quartzchestplate" : "Kwarcowy Napierśnik",
  "item.supertools.quartzleggings" : "Kwarcowe Nogawice",
  "item.supertools.quartzboots" : "Kwarcowe Buty",
  "item.supertools.bonemealtool" : "Torba Mączki Kostnej",
  "item.supertools.superhoe": "Wyśmienita Motyka",
  "item.supertools.superaxe": "Wyśmienita Siekiera",
  "item.supertools.superpickaxe": "Wyśmienity Kilof",
  "item.supertools.supershovel": "Wyśmienita Łopata",
  "item.supertools.supersword": "Wyśmienity Miecz",
  "item.supertools.itemcup" : "Puchar",
  "item.supertools.specialcup" : "Wyśmienity Puchar",
  "item.supertools.woodensickle" : "Drewniana Kosa",
  "item.supertools.stonesickle" : "Kamienna Kosa",
  "item.supertools.lapissickle" : "Lazurytowa Kosa",
  "item.supertools.ironsickle" : "Żelazna Kosa",
  "item.supertools.redstonesickle" : "Redstonowa Kosa",
  "item.supertools.goldensickle" : "Złota Kosa",
  "item.supertools.diamondsickle" : "Diamentowa Kosa",
  "item.supertools.emeraldsickle" : "Szmaragdowa Kosa",
  "item.supertools.obsidiansickle" : "Obsydianowa Kosa",
  "item.supertools.quartzsickle" : "Kwarcowa Kosa",
  "item.supertools.supersickle" : "Wyśmienita Kosa",
  "advancements.supertools.root.title" : "Wyśmienite Narzędzia",
  "advancements.supertools.root.description" : "Stwórz każde Wyśmienite Narzędzie!",
  "advancements.supertools.superaxe.title" : "Wyśmienita Siekiera",
  "advancements.supertools.superaxe.description" : "Czyż to nie Wyśmienita Siekiera?",
  "advancements.supertools.superpickaxe.title" : "Wyśmienity Kilof",
  "advancements.supertools.superpickaxe.description" : "Czyż to nie Wyśmienity Kilof?",
  "advancements.supertools.supershovel.title" : "Super Łopata",
  "advancements.supertools.supershovel.description" : "Czyż to nie Wyśmienita Łopata?",
  "advancements.supertools.superhoe.title" : "Super Motyka",
  "advancements.supertools.superhoe.description" : "Czyż to nie Wyśmienita Motyka?",
  "advancements.supertools.supersword.title" : "Super Miecz",
  "advancements.supertools.supersword.description" : "Czyż to nie Wyśmienity Miecz?",
  "advancements.supertools.supersickle.title" : "Super Sickle",
  "advancements.supertools.supersickle.description" : "Czyż to nie Wyśmienita Kosa?",
  "advancements.supertools.bonemealtool.title" : "Torba Mączki Kostnej?",
  "advancements.supertools.bonemealtool.description" : "Dlaczego nie użyjesz jej do nawożenia swoich roślin?",
  "advancements.supertools.cup.title" : "PUCHAR!",
  "advancements.supertools.cup.description" : "Tym da się kopać?",
  "advancements.supertools.specialcup.title" : "WYŚMIENITY PUCHAR!",
  "advancements.supertools.specialcup.description" : "Teraz jesteś gotów do walki!"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the next version.
