### ISSUE TITLE
Parsing error loading recipe supertools:platinum_sickle

### ISSUE THREAD

**Issue by serpi90** [TheKiritoPlayer20/Forge-Mods#9]
**Describe the bug**
Error when loading the mod:

**Versions**
Forge version: forge-1.15.1-30.0.19
Supertools version: 1.0b_1.15.1

**To Reproduce**
1. Start the server
2. See the log
3. find this: ```text/plain
 [Server thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe supertools:platinum_sickle
com.google.gson.JsonSyntaxException: Unknown item 'simplyplatinum:platinum_ingot'
```

**Expected behavior**
Either the recipe should load, and a dependency mod is required, or the recipe is invalid.

**Additional context**
The mod still works, but this should not happen.

**Comment by realKG20** [comment]
It happens, as the platinum sickle is a addon for the mod "Simple Platinum". Super Tools does not have a platinum ingot on its own.

**Comment by snurre0** [comment]
Is it possible to add any check before loading recipes that has missing dependencies from supported mods?
Getting a big red error on every load is not the nicest thing in the world.

**Comment by realKG20** [comment]
Going to look into it. Easiest might be to make two versions or for you just to remove the recipe.

**Comment by snurre0** [comment]
If it's easy to remove, then I'm all in on that :)
Anything I can easily do without too much minecraft mod experience?

**Comment by realKG20** [comment]
You open the .jar with Winrar or 7zip, go into the data folder then into the recipes folder and then remove the "platinum_sickle.json" file.

**Comment by snurre0** [comment]
Awesome, worked like a charm. Thank you! :)
